// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Category struct {
	IDCategory string
}

type Dish struct {
	IDDish      int64
	Description string
	Name        string
	Image       string
	Price       float64
	IDCategory  string
}

type Invoice struct {
	IDOrder   sql.NullInt64
	IDDish    sql.NullInt64
	CreatedAt time.Time
}

type Order struct {
	IDOrder  int64
	IDDesk   sql.NullInt64
	IDStatus sql.NullString
}

type Status struct {
	IDStatus string
}
